import fs from 'fs';
import path from 'path';
import type { GeneratedBot, BotRule, FindingToFortaMapping } from './types.js';

// Mapping from Slither/Mythril finding types to Forta detection patterns
const FINDING_TO_FORTA_MAP: FindingToFortaMapping[] = [
  {
    auditxFindingType: 'reentrancy-eth',
    fortaRuleId:       'REENTRANCY-WATCH-001',
    fortaBotTemplate:  'reentrancy',
    severity:          'CRITICAL',
    description:       'Monitors for reentrancy attack patterns on functions that transfer ETH',
    triggerCondition:  'Repeated calls with ETH value in same transaction depth >= 3',
  },
  {
    auditxFindingType: 'reentrancy-no-eth',
    fortaRuleId:       'REENTRANCY-WATCH-002',
    fortaBotTemplate:  'reentrancy',
    severity:          'HIGH',
    description:       'Monitors for reentrancy without ETH — state manipulation attacks',
    triggerCondition:  'Repeated calls in same transaction, state change after external call',
  },
  {
    auditxFindingType: 'suicidal',
    fortaRuleId:       'SELFDESTRUCT-WATCH-001',
    fortaBotTemplate:  'admin',
    severity:          'CRITICAL',
    description:       'Monitors for selfdestruct calls — contract destruction events',
    triggerCondition:  'SELFDESTRUCT opcode execution detected',
  },
  {
    auditxFindingType: 'arbitrary-send-eth',
    fortaRuleId:       'DRAIN-WATCH-001',
    fortaBotTemplate:  'drain',
    severity:          'CRITICAL',
    description:       'Monitors for unexpected large ETH sends from contract',
    triggerCondition:  'ETH transfer exceeding 10% of contract balance in single tx',
  },
  {
    auditxFindingType: 'controlled-delegatecall',
    fortaRuleId:       'DELEGATECALL-WATCH-001',
    fortaBotTemplate:  'admin',
    severity:          'HIGH',
    description:       'Monitors for delegatecall to unexpected target addresses',
    triggerCondition:  'DELEGATECALL to non-whitelisted address',
  },
  {
    auditxFindingType: 'tx-origin',
    fortaRuleId:       'TXORIGIN-WATCH-001',
    fortaBotTemplate:  'phishing',
    severity:          'HIGH',
    description:       'Monitors for tx.origin authentication bypass attempts',
    triggerCondition:  'tx.origin !== msg.sender pattern in auth function',
  },
  {
    auditxFindingType: 'weak-prng',
    fortaRuleId:       'RANDOMNESS-WATCH-001',
    fortaBotTemplate:  'manipulation',
    severity:          'MEDIUM',
    description:       'Monitors for block hash / timestamp manipulation in randomness',
    triggerCondition:  'Randomness function called within same block as large bet/deposit',
  },
  {
    auditxFindingType: 'calls-loop',
    fortaRuleId:       'GAS-WATCH-001',
    fortaBotTemplate:  'dos',
    severity:          'MEDIUM',
    description:       'Monitors for DoS via gas exhaustion — abnormal gas usage spikes',
    triggerCondition:  'Transaction gas usage exceeds 3x rolling baseline',
  },
  {
    auditxFindingType: 'unchecked-transfer',
    fortaRuleId:       'TOKEN-DRAIN-001',
    fortaBotTemplate:  'drain',
    severity:          'HIGH',
    description:       'Monitors for unexpected token transfers from contract',
    triggerCondition:  'ERC-20 Transfer event from contract exceeding 5% of balance',
  },
  {
    auditxFindingType: 'missing-zero-check',
    fortaRuleId:       'ADMIN-CHANGE-001',
    fortaBotTemplate:  'admin',
    severity:          'MEDIUM',
    description:       'Monitors for critical admin address changes to zero address',
    triggerCondition:  'Admin/owner address changed to zero address',
  },
];

// Core bot templates — JavaScript source code templates
const BOT_TEMPLATES: Record<string, (contractAddress: string, rules: BotRule[], contractName: string) => string> = {
  reentrancy: (contractAddress, rules, contractName) => `
const { Finding, FindingSeverity, FindingType, ethers } = require('forta-agent');

// AuditX Generated Bot — Reentrancy Monitor
// Contract: ${contractName} (${contractAddress})
// Generated by: AuditX v2.0.0 — github.com/akhilmuvva/auditX
// Generated at: ${new Date().toISOString()}

const TARGET_CONTRACT = '${contractAddress.toLowerCase()}';
const CALL_DEPTH_THRESHOLD = 3;

async function handleTransaction(txEvent) {
  const findings = [];

  // Only monitor target contract
  const involvesTarget = txEvent.addresses.includes(TARGET_CONTRACT);
  if (!involvesTarget) return findings;

  // Count recursive calls to target in this transaction
  const callsToTarget = (txEvent.traces || []).filter(trace =>
    trace.action?.to?.toLowerCase() === TARGET_CONTRACT &&
    trace.action?.value && BigInt(trace.action.value || '0') > 0n
  );

  if (callsToTarget.length >= CALL_DEPTH_THRESHOLD) {
    findings.push(Finding.fromObject({
      name: 'Potential Reentrancy Attack Detected',
      description: \`${contractName} received \${callsToTarget.length} recursive calls with ETH in tx \${txEvent.hash}\`,
      alertId: '${rules[0]?.ruleId || 'REENTRANCY-WATCH-001'}',
      severity: FindingSeverity.Critical,
      type: FindingType.Exploit,
      metadata: {
        target_contract: TARGET_CONTRACT,
        recursive_call_count: callsToTarget.length.toString(),
        tx_hash: txEvent.hash,
        block_number: txEvent.blockNumber.toString(),
        total_value: callsToTarget.reduce((s, t) => s + BigInt(t.action?.value || 0), 0n).toString(),
        generated_by: 'AuditX',
      }
    }));
  }

  return findings;
}

module.exports = { handleTransaction };
`,

  drain: (contractAddress, rules, contractName) => `
const { Finding, FindingSeverity, FindingType, ethers } = require('forta-agent');

// AuditX Generated Bot — Drain Monitor
// Contract: ${contractName} (${contractAddress})
// Generated by: AuditX v2.0.0

const TARGET_CONTRACT = '${contractAddress.toLowerCase()}';
const ETH_DRAIN_THRESHOLD = ethers.utils.parseEther('10'); // 10 ETH

async function handleTransaction(txEvent) {
  const findings = [];

  // Check for large ETH drain
  if (txEvent.from?.toLowerCase() === TARGET_CONTRACT || 
      txEvent.to?.toLowerCase() === TARGET_CONTRACT) {

    const value = ethers.BigNumber.from(txEvent.value || '0');

    if (value.gte(ETH_DRAIN_THRESHOLD)) {
      findings.push(Finding.fromObject({
        name: 'Large ETH Transfer from Monitored Contract',
        description: \`\${ethers.utils.formatEther(value)} ETH moved in/from ${contractName}\`,
        alertId: '${rules[0]?.ruleId || 'DRAIN-WATCH-001'}',
        severity: FindingSeverity.High,
        type: FindingType.Suspicious,
        metadata: {
          target_contract: TARGET_CONTRACT,
          eth_amount: ethers.utils.formatEther(value),
          from: txEvent.from,
          to: txEvent.to,
          tx_hash: txEvent.hash,
          generated_by: 'AuditX',
        }
      }));
    }
  }

  // Check for large ERC-20 token drain
  const transferLogs = txEvent.filterLog(
    'event Transfer(address indexed from, address indexed to, uint256 value)'
  );

  for (const log of transferLogs) {
    if (log.address?.toLowerCase() === TARGET_CONTRACT) {
      findings.push(Finding.fromObject({
        name: 'ERC-20 Token Transfer from Monitored Contract',
        description: \`Token transfer from ${contractName}: \${log.args.value.toString()} tokens\`,
        alertId: 'TOKEN-DRAIN-001',
        severity: FindingSeverity.Medium,
        type: FindingType.Suspicious,
        metadata: {
          token_contract: log.address,
          from: log.args.from,
          to: log.args.to,
          amount: log.args.value.toString(),
          generated_by: 'AuditX',
        }
      }));
    }
  }

  return findings;
}

module.exports = { handleTransaction };
`,

  admin: (contractAddress, rules, contractName) => `
const { Finding, FindingSeverity, FindingType } = require('forta-agent');

// AuditX Generated Bot — Admin Action Monitor
// Contract: ${contractName} (${contractAddress})
// Generated by: AuditX v2.0.0

const TARGET_CONTRACT = '${contractAddress.toLowerCase()}';
const TRUSTED_ADMINS = (process.env.TRUSTED_ADMIN_ADDRESSES || '').split(',').map(a => a.toLowerCase());

async function handleTransaction(txEvent) {
  const findings = [];

  if (!txEvent.addresses.includes(TARGET_CONTRACT)) return findings;

  // Watch for ownership transfer events
  const ownershipLogs = txEvent.filterLog(
    'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
    TARGET_CONTRACT
  );

  for (const log of ownershipLogs) {
    const newOwner = log.args.newOwner?.toLowerCase();
    const isToZero = newOwner === '0x0000000000000000000000000000000000000000';
    const isUntrusted = TRUSTED_ADMINS.length > 0 && !TRUSTED_ADMINS.includes(newOwner);

    findings.push(Finding.fromObject({
      name: isToZero ? 'Ownership Renounced' : 'Ownership Transfer Detected',
      description: \`${contractName} ownership changed from \${log.args.previousOwner} to \${log.args.newOwner}\`,
      alertId: '${rules[0]?.ruleId || 'ADMIN-CHANGE-001'}',
      severity: isToZero ? FindingSeverity.Info :
                isUntrusted ? FindingSeverity.High : FindingSeverity.Medium,
      type: FindingType.Suspicious,
      metadata: {
        target_contract: TARGET_CONTRACT,
        previous_owner: log.args.previousOwner,
        new_owner: log.args.newOwner,
        is_to_zero_address: isToZero.toString(),
        is_untrusted: isUntrusted.toString(),
        tx_hash: txEvent.hash,
        generated_by: 'AuditX',
      }
    }));
  }

  return findings;
}

module.exports = { handleTransaction };
`,

  dos: (contractAddress, rules, contractName) => `
const { Finding, FindingSeverity, FindingType } = require('forta-agent');

// AuditX Generated Bot — DoS / Gas Anomaly Monitor
// Contract: ${contractName} (${contractAddress})
// Generated by: AuditX v2.0.0

const TARGET_CONTRACT = '${contractAddress.toLowerCase()}';
let gasBaseline = { mean: 100000, variance: 0, count: 0 };

function updateBaseline(gasUsed) {
  gasBaseline.count++;
  const delta = gasUsed - gasBaseline.mean;
  gasBaseline.mean += delta / gasBaseline.count;
  const delta2 = gasUsed - gasBaseline.mean;
  gasBaseline.variance += (delta * delta2 - gasBaseline.variance) / gasBaseline.count;
}

function getZScore(gasUsed) {
  const stdDev = Math.sqrt(gasBaseline.variance);
  if (stdDev === 0) return 0;
  return (gasUsed - gasBaseline.mean) / stdDev;
}

async function handleTransaction(txEvent) {
  const findings = [];

  if (!txEvent.addresses.includes(TARGET_CONTRACT)) return findings;

  const gasUsed = Number(txEvent.gasUsed || 0);
  const zScore = getZScore(gasUsed);

  updateBaseline(gasUsed);

  if (zScore >= 3.0 && gasBaseline.count > 10) {
    findings.push(Finding.fromObject({
      name: 'Abnormal Gas Usage — Possible DoS Attack',
      description: \`${contractName} tx used \${gasUsed} gas (z-score: \${zScore.toFixed(2)}, baseline: \${Math.round(gasBaseline.mean)})\`,
      alertId: '${rules[0]?.ruleId || 'GAS-WATCH-001'}',
      severity: zScore >= 5 ? FindingSeverity.High : FindingSeverity.Medium,
      type: FindingType.Suspicious,
      metadata: {
        target_contract: TARGET_CONTRACT,
        gas_used: gasUsed.toString(),
        z_score: zScore.toFixed(2),
        baseline_mean: Math.round(gasBaseline.mean).toString(),
        tx_hash: txEvent.hash,
        generated_by: 'AuditX',
      }
    }));
  }

  return findings;
}

module.exports = { handleTransaction };
`,

  phishing: (contractAddress, rules, contractName) => `
const { Finding, FindingSeverity, FindingType } = require('forta-agent');

// AuditX Generated Bot — Phishing / tx.origin Auth Monitor
// Contract: ${contractName} (${contractAddress})
// Generated by: AuditX v2.0.0

const TARGET_CONTRACT = '${contractAddress.toLowerCase()}';

async function handleTransaction(txEvent) {
  const findings = [];

  if (!txEvent.addresses.includes(TARGET_CONTRACT)) return findings;

  const isContractCaller = txEvent.from?.toLowerCase() !== txEvent.transaction?.from?.toLowerCase();

  if (isContractCaller) {
    findings.push(Finding.fromObject({
      name: 'Indirect Contract Call — Possible tx.origin Phishing',
      description: \`${contractName} called indirectly. If it uses tx.origin auth, this may be a phishing attack.\`,
      alertId: '${rules[0]?.ruleId || 'TXORIGIN-WATCH-001'}',
      severity: FindingSeverity.Medium,
      type: FindingType.Suspicious,
      metadata: {
        target_contract: TARGET_CONTRACT,
        tx_origin: txEvent.transaction?.from,
        msg_sender: txEvent.from,
        tx_hash: txEvent.hash,
        generated_by: 'AuditX',
      }
    }));
  }

  return findings;
}

module.exports = { handleTransaction };
`,

  manipulation: (contractAddress, rules, contractName) => `
const { Finding, FindingSeverity, FindingType } = require('forta-agent');

// AuditX Generated Bot — Randomness Manipulation Monitor
// Contract: ${contractName} (${contractAddress})
// Generated by: AuditX v2.0.0

const TARGET_CONTRACT = '${contractAddress.toLowerCase()}';
const SUSPICIOUS_VALUE_THRESHOLD = BigInt('1000000000000000000'); // 1 ETH

async function handleTransaction(txEvent) {
  const findings = [];

  if (!txEvent.addresses.includes(TARGET_CONTRACT)) return findings;

  const value = BigInt(txEvent.value || '0');

  if (value >= SUSPICIOUS_VALUE_THRESHOLD) {
    findings.push(Finding.fromObject({
      name: 'High-Value Transaction to Weak Randomness Contract',
      description: \`High-value tx to ${contractName} which has weak randomness. Possible manipulation attempt.\`,
      alertId: '${rules[0]?.ruleId || 'RANDOMNESS-WATCH-001'}',
      severity: FindingSeverity.Medium,
      type: FindingType.Suspicious,
      metadata: {
        target_contract: TARGET_CONTRACT,
        value_eth: (Number(value) / 1e18).toFixed(4),
        from: txEvent.from,
        tx_hash: txEvent.hash,
        generated_by: 'AuditX',
      }
    }));
  }

  return findings;
}

module.exports = { handleTransaction };
`,
};

// Main function: generate a Forta bot from AuditX findings
export async function generateFortaBot(
  findings: Array<{ tool?: string; severity?: string; title?: string }>,
  contractAddress: string,
  contractName: string
): Promise<GeneratedBot | null> {
  console.log(`[Forta] Analyzing ${findings.length} findings for bot auto-generation...`);

  // Map each finding to mapped rules
  const matchedRules: BotRule[] = [];
  let primaryTemplate: string | null = null;
  let highestSeverityRank = -1;

  const severityRanks: Record<string, number> = {
    CRITICAL: 4,
    HIGH: 3,
    MEDIUM: 2,
    LOW: 1,
    INFO: 0
  };

  const titleLower = findings.map(f => (f.title || '').toLowerCase());

  for (const mapping of FINDING_TO_FORTA_MAP) {
    // Check if finding keyword matches finding title or description
    const isMatched = titleLower.some(t => 
      t.includes(mapping.auditxFindingType.replace('-', ' ')) ||
      t.includes(mapping.auditxFindingType.split('-')[0])
    );

    if (isMatched) {
      const ruleRank = severityRanks[mapping.severity] || 0;
      
      matchedRules.push({
        ruleId: mapping.fortaRuleId,
        description: mapping.description,
        severity: mapping.severity,
        triggerOn: mapping.triggerCondition
      });

      if (ruleRank > highestSeverityRank) {
        highestSeverityRank = ruleRank;
        primaryTemplate = mapping.fortaBotTemplate;
      }
    }
  }

  // Fallback: If no custom vulnerability mapped, check if there are high/critical findings generally
  if (matchedRules.length === 0) {
    const criticalOrHigh = findings.filter(f => 
      f.severity?.toUpperCase() === 'CRITICAL' || f.severity?.toUpperCase() === 'HIGH'
    );
    
    if (criticalOrHigh.length > 0) {
      // Use general balance drain alert as default fallback
      const defaultMapping = FINDING_TO_FORTA_MAP.find(m => m.fortaBotTemplate === 'drain')!;
      matchedRules.push({
        ruleId: defaultMapping.fortaRuleId,
        description: defaultMapping.description,
        severity: defaultMapping.severity,
        triggerOn: defaultMapping.triggerCondition
      });
      primaryTemplate = 'drain';
    }
  }

  if (matchedRules.length === 0 || !primaryTemplate) {
    console.log('[Forta] No monitorable patterns or critical vulnerabilities found. Bot generation skipped.');
    return null;
  }

  // Generate bot source code
  const sourceCode = BOT_TEMPLATES[primaryTemplate](contractAddress, matchedRules, contractName);

  return {
    sourceCode,
    botName: `AuditX Monitor — ${contractName}`,
    description: `Auto-generated by AuditX. Monitors: ${matchedRules.map(r => r.description).join(', ')}`,
    rules: matchedRules,
    contractAddress,
    generatedAt: Date.now()
  };
}

// Save generated bot to disk for user to deploy
export async function saveFortaBot(
  bot: GeneratedBot,
  outputDir: string
): Promise<string> {
  const botDirName = `${bot.botName.replace(/[^a-zA-Z0-9_-]/g, '_')}_monitor`.toLowerCase();
  const botDirPath = path.join(outputDir, 'forta-bots', botDirName);

  fs.mkdirSync(botDirPath, { recursive: true });

  // 1. Write agent.js
  fs.writeFileSync(path.join(botDirPath, 'agent.js'), bot.sourceCode, 'utf8');

  // 2. Write package.json
  const packageJson = {
    name: `@auditx/${botDirName}`,
    version: '1.0.0',
    description: bot.description,
    main: 'agent.js',
    scripts: {
      start: 'npx forta-agent@latest run'
    },
    dependencies: {
      'forta-agent': '^0.1.42'
    }
  };
  fs.writeFileSync(path.join(botDirPath, 'package.json'), JSON.stringify(packageJson, null, 2), 'utf8');

  // 3. Write README.md
  const readmeMd = `# ${bot.botName}

Auto-generated threat monitoring agent created by **AuditX v2.0.0**.

## Description
${bot.description}

## Detection Rules
This agent is deployed with the following active heuristics:
${bot.rules.map(r => `* **${r.ruleId}** [${r.severity}]: ${r.description} (Trigger: \`${r.triggerOn}\`)`).join('\n')}

## Target Contract Address
Monitored address: \`${bot.contractAddress}\`

## Quick Start
To test or deploy this threat detection bot to the Forta Network, follow these simple CLI steps:

\`\`\`bash
# 1. Navigate to the agent directory
cd forta-bots/${botDirName}

# 2. Install dependencies
npm install

# 3. Test the agent locally against target transaction traces
npx forta-agent@latest run --tx <insert_suspicious_tx_hash>

# 4. Deploy your agent to the Forta Network
npx forta-agent@latest push
\`\`\`
`;
  fs.writeFileSync(path.join(botDirPath, 'README.md'), readmeMd, 'utf8');

  return botDirPath;
}
