[package]
name = "auditx-identity-http"
version = "0.1.0"
edition = "2021"

[dependencies]
auditx-identity = { path = "../auditx-identity" }
auditx-core = { path = "../auditx-core" }
axum = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
