[package]
name = "auditx-identity"
version = "0.1.0"
edition = "2021"

[features]
default = []
redis-store = ["redis"]

[dependencies]
auditx-core = { path = "../auditx-core" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
alloy = { workspace = true }
siwe = "0.6"
ethers = { version = "2.0", default-features = false }
uuid = { workspace = true }
redis = { version = "0.26", features = ["tokio-comp", "connection-manager"], optional = true }

[dev-dependencies]
tokio = { workspace = true }
