/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AuditRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRegistry"
      | "agentReputation"
      | "audits"
      | "disputeAudit"
      | "disputeResolver"
      | "disputeTimestamps"
      | "getAuditCount"
      | "resolveDispute"
      | "setDisputeResolver"
      | "submitAudit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditSubmitted"
      | "DisputeRaised"
      | "DisputeResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "audits",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeAudit",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTimestamps",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAudit",
    values: [BytesLike, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "audits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAudit",
    data: BytesLike
  ): Result;
}

export namespace AuditSubmittedEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    auditor: AddressLike,
    ipfsCID: string,
    cvssScore: BigNumberish,
    riskLevel: BigNumberish
  ];
  export type OutputTuple = [
    contractHash: string,
    auditor: string,
    ipfsCID: string,
    cvssScore: bigint,
    riskLevel: bigint
  ];
  export interface OutputObject {
    contractHash: string;
    auditor: string;
    ipfsCID: string;
    cvssScore: bigint;
    riskLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    index: BigNumberish,
    challenger: AddressLike,
    evidenceCID: string
  ];
  export type OutputTuple = [
    contractHash: string,
    index: bigint,
    challenger: string,
    evidenceCID: string
  ];
  export interface OutputObject {
    contractHash: string;
    index: bigint;
    challenger: string;
    evidenceCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    index: BigNumberish,
    fraudProven: boolean
  ];
  export type OutputTuple = [
    contractHash: string,
    index: bigint,
    fraudProven: boolean
  ];
  export interface OutputObject {
    contractHash: string;
    index: bigint;
    fraudProven: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AuditRegistry;
  waitForDeployment(): Promise<this>;

  interface: AuditRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  agentReputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  audits: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        auditor: string;
        contractHash: string;
        ipfsCID: string;
        cvssScore: bigint;
        riskLevel: bigint;
        timestamp: bigint;
        disputed: boolean;
      }
    ],
    "view"
  >;

  disputeAudit: TypedContractMethod<
    [contractHash: BytesLike, index: BigNumberish, evidenceCID: string],
    [void],
    "nonpayable"
  >;

  disputeResolver: TypedContractMethod<[], [string], "view">;

  disputeTimestamps: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getAuditCount: TypedContractMethod<
    [contractHash: BytesLike],
    [bigint],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [contractHash: BytesLike, index: BigNumberish, fraudProven: boolean],
    [void],
    "nonpayable"
  >;

  setDisputeResolver: TypedContractMethod<
    [_disputeResolver: AddressLike],
    [void],
    "nonpayable"
  >;

  submitAudit: TypedContractMethod<
    [
      contractHash: BytesLike,
      ipfsCID: string,
      cvssScore: BigNumberish,
      riskLevel: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentReputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "audits"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        auditor: string;
        contractHash: string;
        ipfsCID: string;
        cvssScore: bigint;
        riskLevel: bigint;
        timestamp: bigint;
        disputed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputeAudit"
  ): TypedContractMethod<
    [contractHash: BytesLike, index: BigNumberish, evidenceCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeResolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputeTimestamps"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuditCount"
  ): TypedContractMethod<[contractHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [contractHash: BytesLike, index: BigNumberish, fraudProven: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDisputeResolver"
  ): TypedContractMethod<[_disputeResolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitAudit"
  ): TypedContractMethod<
    [
      contractHash: BytesLike,
      ipfsCID: string,
      cvssScore: BigNumberish,
      riskLevel: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuditSubmitted"
  ): TypedContractEvent<
    AuditSubmittedEvent.InputTuple,
    AuditSubmittedEvent.OutputTuple,
    AuditSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;

  filters: {
    "AuditSubmitted(bytes32,address,string,uint8,uint8)": TypedContractEvent<
      AuditSubmittedEvent.InputTuple,
      AuditSubmittedEvent.OutputTuple,
      AuditSubmittedEvent.OutputObject
    >;
    AuditSubmitted: TypedContractEvent<
      AuditSubmittedEvent.InputTuple,
      AuditSubmittedEvent.OutputTuple,
      AuditSubmittedEvent.OutputObject
    >;

    "DisputeRaised(bytes32,uint256,address,string)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
  };
}
