/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ResumeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIMELOCK_DELAY"
      | "cancelVerifierUpdate"
      | "executeVerifierUpdate"
      | "minimumThreshold"
      | "owner"
      | "pendingVerifier"
      | "proposeVerifierUpdate"
      | "records"
      | "renounceOwnership"
      | "submitProof"
      | "transferOwnership"
      | "usedNullifiers"
      | "verifier"
      | "verifierUpdateUnlockTime"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProofVerified"
      | "VerifierUpdateCancelled"
      | "VerifierUpdateExecuted"
      | "VerifierUpdateProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelVerifierUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeVerifierUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeVerifierUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "records", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNullifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierUpdateUnlockTime",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelVerifierUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeVerifierUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeVerifierUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedNullifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierUpdateUnlockTime",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [
    submitter: AddressLike,
    nullifier: BytesLike,
    jobId: string
  ];
  export type OutputTuple = [
    submitter: string,
    nullifier: string,
    jobId: string
  ];
  export interface OutputObject {
    submitter: string;
    nullifier: string;
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierUpdateCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierUpdateExecutedEvent {
  export type InputTuple = [newVerifier: AddressLike];
  export type OutputTuple = [newVerifier: string];
  export interface OutputObject {
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierUpdateProposedEvent {
  export type InputTuple = [newVerifier: AddressLike, unlockTime: BigNumberish];
  export type OutputTuple = [newVerifier: string, unlockTime: bigint];
  export interface OutputObject {
    newVerifier: string;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ResumeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ResumeRegistry;
  waitForDeployment(): Promise<this>;

  interface: ResumeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  cancelVerifierUpdate: TypedContractMethod<[], [void], "nonpayable">;

  executeVerifierUpdate: TypedContractMethod<[], [void], "nonpayable">;

  minimumThreshold: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingVerifier: TypedContractMethod<[], [string], "view">;

  proposeVerifierUpdate: TypedContractMethod<
    [_newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  records: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string] & {
        submitter: string;
        timestamp: bigint;
        jobId: string;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitProof: TypedContractMethod<
    [
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish],
      _pubSignals: [BigNumberish, BigNumberish, BigNumberish],
      jobId: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedNullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  verifierUpdateUnlockTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelVerifierUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeVerifierUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "minimumThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeVerifierUpdate"
  ): TypedContractMethod<[_newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string] & {
        submitter: string;
        timestamp: bigint;
        jobId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish],
      _pubSignals: [BigNumberish, BigNumberish, BigNumberish],
      jobId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedNullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierUpdateUnlockTime"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierUpdateCancelled"
  ): TypedContractEvent<
    VerifierUpdateCancelledEvent.InputTuple,
    VerifierUpdateCancelledEvent.OutputTuple,
    VerifierUpdateCancelledEvent.OutputObject
  >;
  getEvent(
    key: "VerifierUpdateExecuted"
  ): TypedContractEvent<
    VerifierUpdateExecutedEvent.InputTuple,
    VerifierUpdateExecutedEvent.OutputTuple,
    VerifierUpdateExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierUpdateProposed"
  ): TypedContractEvent<
    VerifierUpdateProposedEvent.InputTuple,
    VerifierUpdateProposedEvent.OutputTuple,
    VerifierUpdateProposedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProofVerified(address,bytes32,string)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;

    "VerifierUpdateCancelled()": TypedContractEvent<
      VerifierUpdateCancelledEvent.InputTuple,
      VerifierUpdateCancelledEvent.OutputTuple,
      VerifierUpdateCancelledEvent.OutputObject
    >;
    VerifierUpdateCancelled: TypedContractEvent<
      VerifierUpdateCancelledEvent.InputTuple,
      VerifierUpdateCancelledEvent.OutputTuple,
      VerifierUpdateCancelledEvent.OutputObject
    >;

    "VerifierUpdateExecuted(address)": TypedContractEvent<
      VerifierUpdateExecutedEvent.InputTuple,
      VerifierUpdateExecutedEvent.OutputTuple,
      VerifierUpdateExecutedEvent.OutputObject
    >;
    VerifierUpdateExecuted: TypedContractEvent<
      VerifierUpdateExecutedEvent.InputTuple,
      VerifierUpdateExecutedEvent.OutputTuple,
      VerifierUpdateExecutedEvent.OutputObject
    >;

    "VerifierUpdateProposed(address,uint256)": TypedContractEvent<
      VerifierUpdateProposedEvent.InputTuple,
      VerifierUpdateProposedEvent.OutputTuple,
      VerifierUpdateProposedEvent.OutputObject
    >;
    VerifierUpdateProposed: TypedContractEvent<
      VerifierUpdateProposedEvent.InputTuple,
      VerifierUpdateProposedEvent.OutputTuple,
      VerifierUpdateProposedEvent.OutputObject
    >;
  };
}
